# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '15 8 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@master
      
    # Setup Node
    - name: Install Node V12
      uses: actions/setup-node@master
      with:
        node-version: 12

    # Runs a single command using the runners shell
    - name: Check Node Version
      run: node -v

    # Runs a set of commands using the runners shell
    - name: Install Dependencies
      run: yarn install
    
    # Update time in README.md
    - name: Update README.md
      run: yarn update:readme
    
    # Commit change and push to repository
    - name: Commit and push
      uses: khaazz/action-autocommit@master
